const aniversaris = {
    "11-01": "Albert Campins", 
    "29-09": "Miguel Arroyo", 
    "05-11": "Cristina Santiago", 
    "08-03": "Cristina Vega", 
    "25-05": "Helena Pajares", 
    "30-08": "Beatriz Julián", 
    "10-12": "Aleix Prat", 
    "02-12": "Javier Frias", 
    "01-01": "Laura Navarro", 
    "07-06": "Alfonso Primo", 
    "19-04": "Alejandro García"
};


const calendari = {
    // GENER
    "01-01": { ca: "Cap d'Any ✨", es: "Año Nuevo ✨" }, "02-01": { ca: "Dia del Policia 👮", es: "Día del Policía 👮" }, "03-01": { ca: "Dia de la Salut de la Ment 🧠", es: "Día de la Salud Mental 🧠" }, "04-01": { ca: "Dia del Braille ⠃", es: "Día del Braille ⠃" }, "05-01": { ca: "Nit de Reis 👑", es: "Noche de Reyes 👑" }, "06-01": { ca: "Dia de Reis 🎁", es: "Día de Reyes 🎁" }, "07-01": { ca: "Inici de Rebaixes 🛍️", es: "Inicio de Rebajas 🛍️" }, "08-01": { ca: "Dia del Batre 🥁", es: "Día de la Batería 🥁" }, "09-01": { ca: "Dia de l'Ascens 🧗", es: "Día del Ascenso 🧗" }, "10-01": { ca: "Dia de la Gent Peculiar 🤪", es: "Día de la Gente Peculiar 🤪" }, "11-01": { ca: "Dia de planificar l'any 📅", es: "Día de planificar el año 📅" }, "12-01": { ca: "Dia del petó pèl-roig 👨‍🦰", es: "Día del beso pelirrojo 👨‍🦰" }, "13-01": { ca: "Dia del Xandall 👕", es: "Día del Chándal 👕" }, "14-01": { ca: "Dia de la Logística 📦", es: "Día de la Logística 📦" }, "15-01": { ca: "Dia del Barret 🎩", es: "Día del Sombrero 🎩" }, "16-01": { ca: "Dia de la Croqueta 🥟", es: "Día de la Croqueta 🥟" }, "17-01": { ca: "Sant Antoni (Dels Animals) 🐶", es: "San Antonio (De los Animales) 🐶" }, "18-01": { ca: "Dia de Winnie the Pooh 🧸", es: "Día de Winnie the Pooh 🧸" }, "19-01": { ca: "Dia de les crispetes 🍿", es: "Día de las palomitas 🍿" }, "20-01": { ca: "Dia dels Pingüins 🐧", es: "Día de los Pingüinos 🐧" }, "21-01": { ca: "Dia de l'Abraçada 🤗", es: "Día del Abrazo 🤗" }, "22-01": { ca: "Dia de la Salsa Picant 🌶️", es: "Día de la Salsa Picante 🌶️" }, "23-01": { ca: "Dia de l'Escriptura a mà ✍️", es: "Día de la Escritura a mano ✍️" }, "24-01": { ca: "Dia del Periodista 📰", es: "Día del Periodista 📰" }, "25-01": { ca: "Dia de l'Infern 🤘", es: "Día del Infierno 🤘" }, "26-01": { ca: "Dia de l'Educació Ambiental 🌳", es: "Día de la Educación Ambiental 🌳" }, "27-01": { ca: "Dia de l'Holocaust 🕯️", es: "Día del Holocausto 🕯️" }, "28-01": { ca: "Dia de Lego 🧱", es: "Día de Lego 🧱" }, "29-01": { ca: "Dia del Puzle 🧩", es: "Día del Puzzle 🧩" }, "30-01": { ca: "Dia de la Pau 🕊️", es: "Día de la Paz 🕊️" }, "31-01": { ca: "Dia de la Magia 🪄", es: "Día de la Magia 🪄" },

    // FEBRER
    "01-02": { ca: "Dia del Galgo 🐕", es: "Día del Galgo 🐕" }, "02-02": { ca: "La Candelera / Marmota 🐿️", es: "La Candelaria / Marmota 🐿️" }, "03-02": { ca: "Sant Blai 🍬", es: "San Blas 🍬" }, "04-02": { ca: "Dia contra el Càncer 🎗️", es: "Día contra el Cáncer 🎗️" }, "05-02": { ca: "Dia de la Nutella 🍫", es: "Día de la Nutella 🍫" }, "06-02": { ca: "Dia de Bob Marley 🇯🇲", es: "Día de Bob Marley 🇯🇲" }, "07-02": { ca: "Dia de l'Internet Segur 🔒", es: "Día de Internet Seguro 🔒" }, "08-02": { ca: "Dia de l'Òpera 🎭", es: "Día de la Ópera 🎭" }, "09-02": { ca: "Dia de la Pizza 🍕", es: "Día de la Pizza 🍕" }, "10-02": { ca: "Dia dels Llegums 🍲", es: "Día de las Legumbres 🍲" }, "11-02": { ca: "Dona i Ciència 🧪", es: "Mujer y Ciencia 🧪" }, "12-02": { ca: "Santa Eulàlia ⛪ / Darwin 🧬", es: "Santa Eulalia ⛪ / Darwin 🧬" }, "13-02": { ca: "Dia de la Ràdio 📻", es: "Día de la Radio 📻" }, "14-02": { ca: "Sant Valentí ❤️", es: "San Valentín ❤️" }, "15-02": { ca: "Càncer Infantil 🧸", es: "Cáncer Infantil 🧸" }, "16-02": { ca: "Dia de l'Ametlla 🥜", es: "Día de la Almendra 🥜" }, "17-02": { ca: "Dia de la Bondat 🤝", es: "Día de la Bondad 🤝" }, "18-02": { ca: "Dia de l'Asperger 🧩", es: "Día del Asperger 🧩" }, "19-02": { ca: "Dia de les Balenes 🐋", es: "Día de las Ballenas 🐋" }, "20-02": { ca: "Justícia Social ⚖️", es: "Justicia Social ⚖️" }, "21-02": { ca: "Llengua Materna 🗣️", es: "Lengua Materna 🗣️" }, "22-02": { ca: "Igualtat Salarial 💰", es: "Igualdad Salarial 💰" }, "23-02": { ca: "Dia del Compromís 💍", es: "Día del Compromiso 💍" }, "24-02": { ca: "Dia del Barman 🍸", es: "Día del Barman 🍸" }, "25-02": { ca: "Dia del Revolver 🔫", es: "Día del Revolver 🔫" }, "26-02": { ca: "Dia del Pistatxo 🥜", es: "Día del Pistacho 🥜" }, "27-02": { ca: "Dia de l'Ós Polar 🧊", es: "Día del Oso Polar 🧊" }, "28-02": { ca: "Malalties Rares 🧬", es: "Enfermedades Raras 🧬" }, "29-02": { ca: "Dia de l'Any de Traspàs 🌀", es: "Día del Año Bisiesto 🌀" },

    // MARÇ
    "01-03": { ca: "Illes Balears 🏖️", es: "Islas Baleares 🏖️" }, "02-03": { ca: "Dia de llegir 📚", es: "Día de leer 📚" }, "03-03": { ca: "Dia de la Natura 🌿", es: "Día de la Naturaleza 🌿" }, "04-03": { ca: "Dia de l'Enginyeria 🏗️", es: "Día de la Ingeniería 🏗️" }, "05-03": { ca: "Eficiència Energètica 💡", es: "Eficiencia Energética 💡" }, "06-03": { ca: "Dia de l'Escultor 🗿", es: "Día del Escultor 🗿" }, "07-03": { ca: "Dia del Cereal 🥣", es: "Día del Cereal 🥣" }, "08-03": { ca: "Dia de la Dona ♀️", es: "Día de la Mujer ♀️" }, "09-03": { ca: "Dia de la Truita de Patates 🍳", es: "Día de la Tortilla de Patatas 🍳" }, "10-03": { ca: "Dia de Mario Bros (Mar10) 🍄", es: "Día de Mario Bros 🍄" }, "11-03": { ca: "Víctimes del Terrorisme 🕊️", es: "Víctimas del Terrorismo 🕊️" }, "12-03": { ca: "Dia del Glaucoma 👀", es: "Día del Glaucoma 👀" }, "13-03": { ca: "Dia del Somni 💤", es: "Día del Sueño 💤" }, "14-03": { ca: "Dia del número Pi 🥧", es: "Día del número Pi 🥧" }, "15-03": { ca: "Dia del Consumidor 🛒", es: "Día del Consumidor 🛒" }, "16-03": { ca: "Dia del Cavall 🐎", es: "Día del Caballo 🐎" }, "17-03": { ca: "St. Patrick's Day ☘️", es: "St. Patrick's Day ☘️" }, "18-03": { ca: "Dia del Reciclatge ♻️", es: "Día del Reciclaje ♻️" }, "19-03": { ca: "Dia del Pare / St. Josep 👔", es: "Día del Padre / San José 👔" }, "20-03": { ca: "Primavera i Felicitat 😊🌸", es: "Primavera y Felicidad 😊🌸" }, "21-03": { ca: "Poesia i Síndrome de Down 📖", es: "Poesía y Síndrome de Down 📖" }, "22-03": { ca: "Dia de l'Aigua 💧", es: "Día del Agua 💧" }, "23-03": { ca: "Dia del Meteoròleg ☀️", es: "Día del Meteorólogo ☀️" }, "24-03": { ca: "Dia de la Tuberculosi 🩺", es: "Día de la Tuberculosis 🩺" }, "25-03": { ca: "Dia del Goig ✨", es: "Día del Gozo ✨" }, "26-03": { ca: "Dia del Clima 🌍", es: "Día del Clima 🌍" }, "27-03": { ca: "Dia del Teatre 🎭", es: "Día del Teatro 🎭" }, "28-03": { ca: "Dia del Piano 🎹", es: "Día del Piano 🎹" }, "29-03": { ca: "Dia de l'Escacs ♟️", es: "Día del Ajedrez ♟️" }, "30-03": { ca: "Dia del Metge 🩺", es: "Día del Médico 🩺" }, "31-03": { ca: "Visibilitat Trans 🏳️‍⚧️", es: "Visibilidad Trans 🏳️‍⚧️" },

    // ABRIL
    "01-04": { ca: "Dia dels Enganyats 🃏", es: "Día de las Bromas 🃏" }, "02-04": { ca: "Dia de l'Autisme 🧩", es: "Día del Autismo 🧩" }, "03-04": { ca: "Dia del Modelatge 🎨", es: "Día del Modelaje 🎨" }, "04-04": { ca: "Dia de les mines 💣", es: "Día de las minas 💣" }, "05-04": { ca: "Dia de la Consciència 🧘", es: "Día de la Conciencia 🧘" }, "06-04": { ca: "Dia de l'Esport 🏃", es: "Día del Deporte 🏃" }, "07-04": { ca: "Dia de la Salut 🍎", es: "Día de la Salud 🍎" }, "08-04": { ca: "Dia del Poble Gitano 💃", es: "Día del Pueblo Gitano 💃" }, "09-04": { ca: "Dia de l'ASMR 🎧", es: "Día del ASMR 🎧" }, "10-04": { ca: "Dia del Germà 👦👧", es: "Día del Hermano 👦👧" }, "11-04": { ca: "Dia del Parkinson 🧠", es: "Día del Parkinson 🧠" }, "12-04": { ca: "Dia de l'Espai 🚀", es: "Día del Espacio 🚀" }, "13-04": { ca: "Dia del Bes 💋", es: "Día del Beso 💋" }, "14-04": { ca: "Dia de la República 💜", es: "Día de la República 💜" }, "15-04": { ca: "Dia de l'Art 🎨", es: "Día del Arte 🎨" }, "16-04": { ca: "Dia de la Veu 🗣️", es: "Día de la Voz 🗣️" }, "17-04": { ca: "Dia de l'Hemoília 🩸", es: "Día de la Hemofilia 🩸" }, "18-04": { ca: "Dia dels Monuments 🏰", es: "Día de los Monumentos 🏰" }, "19-04": { ca: "Dia de la Bicicleta 🚲", es: "Día de la Bicicleta 🚲" }, "20-04": { ca: "Dia del Disc de Vinil 💿", es: "Día del Disco de Vinilo 💿" }, "21-04": { ca: "Creativitat i Innovació ✨", es: "Creatividad e Innovación ✨" }, "22-04": { ca: "Dia de la Terra 🌍", es: "Día de la Tierra 🌍" }, "23-04": { ca: "Sant Jordi 🌹📖", es: "San Jorge 🌹📖" }, "24-04": { ca: "Dia del Cafè ☕", es: "Día del Café ☕" }, "25-04": { ca: "Dia del DNA 🧬", es: "Día del ADN 🧬" }, "26-04": { ca: "Propietat Intel·lectual 💡", es: "Propiedad Intelectual 💡" }, "27-04": { ca: "Mare de Déu de Montserrat ⛰️", es: "Virgen de Montserrat ⛰️" }, "28-04": { ca: "Seguretat al Treball 👷", es: "Seguridad en el Trabajo 👷" }, "29-04": { ca: "Dia de la Dansa 💃", es: "Día de la Danza 💃" }, "30-04": { ca: "Dia del Jazz 🎷", es: "Día del Jazz 🎷" },

    // MAIG
    "01-05": { ca: "Dia del Treballador 🛠️", es: "Día del Trabajador 🛠️" }, "02-05": { ca: "Contra el Bullying 🚫", es: "Contra el Bullying 🚫" }, "03-05": { ca: "Llibertat de Premsa 🗞️", es: "Libertad de Prensa 🗞️" }, "04-05": { ca: "Star Wars Day ✨", es: "Star Wars Day ✨" }, "05-05": { ca: "Dia del Llebrer 🐕", es: "Día del Galgo 🐕" }, "06-05": { ca: "Dia sense Dietes 🍰", es: "Día sin Dietas 🍰" }, "07-05": { ca: "Dia del Riu 🌊", es: "Día del Río 🌊" }, "08-05": { ca: "Creu Roja 🏥", es: "Cruz Roja 🏥" }, "09-05": { ca: "Dia d'Europa 🇪🇺", es: "Día de Europa 🇪🇺" }, "10-05": { ca: "Dia del Lupus 🦋", es: "Día del Lupus 🦋" }, "11-05": { ca: "Dia de les cançons 🎶", es: "Día de las canciones 🎶" }, "12-05": { ca: "Infermeria 🩺", es: "Enfermería 🩺" }, "13-05": { ca: "Dia del Còctel 🍸", es: "Día del Cóctel 🍸" }, "14-05": { ca: "Dia de l'Assegurança 🛡️", es: "Día del Seguro 🛡️" }, "15-05": { ca: "Dia de la Família 🏠", es: "Día de la Familia 🏠" }, "16-05": { ca: "Dia de la Llum 💡", es: "Día de la Luz 💡" }, "17-05": { ca: "Internet / Contra LGTBIfòbia 🏳️‍🌈", es: "Internet / Contra LGTBIfobia 🏳️‍🌈" }, "18-05": { ca: "Dia dels Museus 🏛️", es: "Día de los Museos 🏛️" }, "19-05": { ca: "Donació de Llet 🍼", es: "Donación de Leche 🍼" }, "20-05": { ca: "Dia de les Abelles 🐝", es: "Día de las Abejas 🐝" }, "21-05": { ca: "Diversitat Cultural 🌍", es: "Diversidad Cultural 🌍" }, "22-05": { ca: "Biodiversitat 🦋", es: "Biodiversidad 🦋" }, "23-05": { ca: "Dia de la Tortuga 🐢", es: "Día de la Tortuga 🐢" }, "24-05": { ca: "Parcs Naturals 🏞️", es: "Parques Naturales 🏞️" }, "25-05": { ca: "Orgull Friki 🤓", es: "Orgullo Friki 🤓" }, "26-05": { ca: "Dia de Dràcula 🧛", es: "Día de Drácula 🧛" }, "27-05": { ca: "Dia del Celíac 🍞", es: "Día del Celíaco 🍞" }, "28-05": { ca: "Dia de l'Hamburguesa 🍔", es: "Día de la Hamburguesa 🍔" }, "29-05": { ca: "Dia de la Pau ONU 🇺🇳", es: "Día de la Paz ONU 🇺🇳" }, "30-05": { ca: "Dia de les Canàries 🇮🇨", es: "Día de Canarias 🇮🇨" }, "31-05": { ca: "Dia sense Fum 🚭", es: "Día sin Humo 🚭" },

    // JUNY
    "01-06": { ca: "Dia dels Pares 👨‍👩‍👧", es: "Día de los Padres 👨‍👩‍👧" }, "02-06": { ca: "Dia del Donut 🍩", es: "Día del Donut 🍩" }, "03-06": { ca: "Dia de la Bicicleta 🚲", es: "Día de la Bicicleta 🚲" }, "04-06": { ca: "Nens Víctimes d'Agressió 👶", es: "Niños Víctimas de Agresión 👶" }, "05-06": { ca: "Medi Ambient 🌲", es: "Medio Ambiente 🌲" }, "06-06": { ca: "Dia de la Llengua Russa 🇷🇺", es: "Día de la Lengua Rusa 🇷🇺" }, "07-06": { ca: "Seguretat Alimentària 🍏", es: "Seguridad Alimentaria 🍏" }, "08-06": { ca: "Dia dels Oceans 🌊", es: "Día de los Océanos 🌊" }, "09-06": { ca: "Dia dels Arxius 📂", es: "Día de los Archivos 📂" }, "10-06": { ca: "Dia del Gelat 🍦", es: "Día del Helado 🍦" }, "11-06": { ca: "Dia del Càncer de Pròstata 🎗️", es: "Día del Cáncer de Próstata 🎗️" }, "12-06": { ca: "Contra Treball Infantil 🧱", es: "Contra Trabajo Infantil 🧱" }, "13-06": { ca: "Dia de l'Albinisme ⚪", es: "Día del Albinismo ⚪" }, "14-06": { ca: "Donant de Sang 🩸", es: "Donante de Sangre 🩸" }, "15-06": { ca: "Contra l'abús a la gent gran 👴", es: "Contra el abuso a los mayores 👴" }, "16-06": { ca: "Dia de les Tortugues Marines 🐢", es: "Día de las Tortugas Marinas 🐢" }, "17-06": { ca: "Contra la Desertificació 🏜️", es: "Contra la Desertificación 🏜️" }, "18-06": { ca: "Gastronomia Sostenible 🥗", es: "Gastronomía Sostenible 🥗" }, "19-06": { ca: "Dia del Surf 🏄", es: "Día del Surf 🏄" }, "20-06": { ca: "Dia del Refugiat ⛺", es: "Día del Refugiado ⛺" }, "21-06": { ca: "Estiu / Música / Yoga ☀️🧘", es: "Verano / Música / Yoga ☀️🧘" }, "22-06": { ca: "Dia del VW Beetle 🚗", es: "Día del VW Beetle 🚗" }, "23-06": { ca: "Nit de Sant Joan 🔥", es: "Noche de San Juan 🔥" }, "24-06": { ca: "Sant Joan 🎆", es: "San Juan 🎆" }, "25-06": { ca: "Dia del Vitiligo ⚪", es: "Día del Vitíligo ⚪" }, "26-06": { ca: "Contra la Droga 🚫", es: "Contra la Droga 🚫" }, "27-06": { ca: "Dia de les PIMES 🏢", es: "Día de las PYMES 🏢" }, "28-06": { ca: "Orgull LGTBIQ+ 🌈", es: "Orgullo LGTBIQ+ 🌈" }, "29-06": { ca: "Sant Pere i Sant Pau ⚓", es: "San Pedro y San Pablo ⚓" }, "30-06": { ca: "Dia de l'Asteroide ☄️", es: "Día del Asteroide ☄️" },

    // JULIOL
    "01-07": { ca: "Rebaixes d'Estiu 👕", es: "Rebajas de Verano 👕" }, "02-07": { ca: "Dia dels OVNIS 🛸", es: "Día de los OVNIS 🛸" }, "03-07": { ca: "Sense Bosses Plàstic 🛍️", es: "Sin Bolsas de Plástico 🛍️" }, "04-07": { ca: "Ebooks 📱", es: "Ebooks 📱" }, "05-07": { ca: "Dia del Bikini 👙", es: "Día del Bikini 👙" }, "06-07": { ca: "Dia del Bes robat 💋", es: "Día del Beso robado 💋" }, "07-07": { ca: "Sant Fermín 🐂", es: "San Fermín 🐂" }, "08-07": { ca: "Dia de les Al·lèrgies 🤧", es: "Día de las Alergias 🤧" }, "09-07": { ca: "Dia de la Moda 👗", es: "Día de la Moda 👗" }, "10-07": { ca: "Sant Cristòfol (Patró Conductors) 🚗", es: "San Cristóbal (Patrón Conductores) 🚗" }, "11-07": { ca: "Dia de la Població 🌍", es: "Día de la Población 🌍" }, "12-07": { ca: "Dia de Malala 👧", es: "Día de Malala 👧" }, "13-07": { ca: "Dia del Rock 🤘", es: "Día del Rock 🤘" }, "14-07": { ca: "Dia del Ximpanzé 🐒", es: "Día del Chimpancé 🐒" }, "15-07": { ca: "Habilitats Joventut 🧑‍🎓", es: "Habilidades de la Juventud 🧑‍🎓" }, "16-07": { ca: "Mare de Déu del Carme ⚓", es: "Virgen del Carmen ⚓" }, "17-07": { ca: "Dia de l'Emoji 😀", es: "Día del Emoji 😀" }, "18-07": { ca: "Nelson Mandela 🕊️", es: "Nelson Mandela 🕊️" }, "19-07": { ca: "Dia dels castells 💪", es: "Día de los castillos 💪" }, "20-07": { ca: "Dia de la Lluna 🌙", es: "Día de la Luna 🌙" }, "21-07": { ca: "Dia del Gos 🐶", es: "Día del Perro 🐶" }, "22-07": { ca: "Dia del Cervell 🧠", es: "Día del Cerebro 🧠" }, "23-07": { ca: "Dia de les Balenes 🐋", es: "Día de las Ballenas 🐋" }, "24-07": { ca: "Dia de l'Autocura 🧴", es: "Día del Autocuidado 🧴" }, "25-07": { ca: "Sant Jaume 🐚", es: "Santiago 🐚" }, "26-07": { ca: "Dia dels Avis 👴👵", es: "Día de los Abuelos 👴👵" }, "27-07": { ca: "Dia del Gos Calent 🌭", es: "Día del Perrito Caliente 🌭" }, "28-07": { ca: "Dia de l'Hepatitis 🩺", es: "Día de la Hepatitis 🩺" }, "29-07": { ca: "Dia del Tigre 🐯", es: "Día del Tigre 🐯" }, "30-07": { ca: "Dia de l'Amistat 🤝", es: "Día de la Amistad 🤝" }, "31-07": { ca: "Dia del Guardabosc 🌲", es: "Día del Guardabosques 🌲" },

    // AGOST
    "01-08": { ca: "Dia de l'Alegria 😊", es: "Día de la Alegría 😊" }, "02-08": { ca: "Dia de la Cervesa 🍺", es: "Día de la Cerveza 🍺" }, "03-08": { ca: "Dia del Planificació 🗓️", es: "Día de la Planificación 🗓️" }, "04-08": { ca: "Dia de l'Ametlla 🥜", es: "Día de la Almendra 🥜" }, "05-08": { ca: "Dia del Semàfor 🚦", es: "Día del Semáforo 🚦" }, "06-08": { ca: "Dia d'Hiroshima 🕊️", es: "Día de Hiroshima 🕊️" }, "07-08": { ca: "Dia del Far 🗼", es: "Día del Faro 🗼" }, "08-08": { ca: "Dia del Gat 🐱", es: "Día del Gato 🐱" }, "09-08": { ca: "Pobles Indígenes 🏹", es: "Pueblos Indígenas 🏹" }, "10-08": { ca: "Dia del Lleó 🦁", es: "Día del León 🦁" }, "11-08": { ca: "Dia del Hip-Hop 🎤", es: "Día del Hip-Hop 🎤" }, "12-08": { ca: "Dia de la Joventut 👱", es: "Día de la Juventud 👱" }, "13-08": { ca: "Dia dels Esquerrans ✍️", es: "Día de los Zurdos ✍️" }, "14-08": { ca: "Dia del llangardaix 🦎", es: "Día del lagarto 🦎" }, "15-08": { ca: "L'Assumpció ⛪", es: "La Asunción ⛪" }, "16-08": { ca: "Dia de la Muntanya Russa 🎢", es: "Día de la Montaña Rusa 🎢" }, "17-08": { ca: "Dia del Peó de Camins 🚧", es: "Día del Peón de Caminos 🚧" }, "18-08": { ca: "Dia de la prevenció d'incendis 🔥", es: "Día de la prevención de incendios 🔥" }, "19-08": { ca: "Dia de la Fotografia 📸", es: "Día de la Fotografía 📸" }, "20-08": { ca: "Dia de la Patata Freda 🍟", es: "Día de la Patata Frita 🍟" }, "21-08": { ca: "Dia de l'Emprenedor 💼", es: "Día del Emprendedor 💼" }, "22-08": { ca: "Dia del Folklore 🎻", es: "Día del Folklore 🎻" }, "23-08": { ca: "Dia de l'Internauta 🖱️", es: "Día del Internauta 🖱️" }, "24-08": { ca: "Sant Bartomeu 🔪", es: "San Bartolomé 🔪" }, "25-08": { ca: "Dia de la Perruqueria 💇", es: "Día de la Peluquería 💇" }, "26-08": { ca: "Dia del Gos (USA) 🐕", es: "Día del Perro (USA) 🐕" }, "27-08": { ca: "Dia del Boxeig 🥊", es: "Día del Boxeo 🥊" }, "28-08": { ca: "Dia dels Avis (Mèxic) 👴", es: "Día de los Abuelos (México) 👴" }, "29-08": { ca: "Dia del Videojoc 🎮", es: "Día del Videojuego 🎮" }, "30-08": { ca: "Dia dels Desapareguts 🕯️", es: "Día de los Desaparecidos 🕯️" }, "31-08": { ca: "Dia de la Solidaritat 🤝", es: "Día de la Solidaridad 🤝" },

    // SETEMBRE
    "01-09": { ca: "Dia de l'Escriptura 📝", es: "Día de la Escritura 📝" }, "02-09": { ca: "Dia del Coco 🥥", es: "Día del Coco 🥥" }, "03-09": { ca: "Dia del Gratacels 🏙️", es: "Día de los Rascacielos 🏙️" }, "04-09": { ca: "Dia del Taekwondo 🥋", es: "Día del Taekwondo 🥋" }, "05-09": { ca: "Dia de la Beneficència ❤️", es: "Día de la Beneficencia ❤️" }, "06-09": { ca: "Dia de llegir un llibre 📖", es: "Día de leer un libro 📖" }, "07-09": { ca: "Dia de l'Aire Net 🌬️", es: "Día del Aire Limpio 🌬️" }, "08-09": { ca: "Alfabetització 📚", es: "Alfabetización 📚" }, "09-09": { ca: "Dia del Cotxe Elèctric ⚡", es: "Día del Coche Eléctrico ⚡" }, "10-09": { ca: "Prevenció del Suïcidi 🎗️", es: "Prevención del Suicidio 🎗️" }, "11-09": { ca: "Diada de Catalunya 🎗️", es: "Diada de Cataluña 🎗️" }, "12-09": { ca: "Dia del Programador (any bisest) 💻", es: "Día del Programador (año bisiesto) 💻" }, "13-09": { ca: "Dia del Programador 💻 / Xocolata 🍫", es: "Día del Programador 💻 / Chocolate 🍫" }, "14-09": { ca: "Dia del Pensament 💡", es: "Día del Pensamiento 💡" }, "15-09": { ca: "Dia de la Democràcia 🗳️", es: "Día de la Democracia 🗳️" }, "16-09": { ca: "Capa d'Ozó 🌍", es: "Capa de Ozono 🌍" }, "17-09": { ca: "Seguretat del Pacient 🏥", es: "Seguridad del Paciente 🏥" }, "18-09": { ca: "Igualtat Salarial ⚖️", es: "Igualdad Salarial ⚖️" }, "19-09": { ca: "Dia de parlar com un pirata 🏴‍☠️", es: "Día de hablar como un pirata 🏴‍☠️" }, "20-09": { ca: "Dia de la Paella 🥘", es: "Día de la Paella 🥘" }, "21-09": { ca: "Pau i Alzheimer 🧠", es: "Paz y Alzheimer 🧠" }, "22-09": { ca: "Tardor / Sense Cotxes 🚗🍂", es: "Otoño / Sin Coches 🚗🍂" }, "23-09": { ca: "Llengües de Signes 🤟", es: "Lenguas de Signos 🤟" }, "24-09": { ca: "La Mercè (Barcelona) 🎡", es: "La Mercè (Barcelona) 🎡" }, "25-09": { ca: "Dia del Farmacèutic 💊", es: "Día del Farmacéutico 💊" }, "26-09": { ca: "Dia de les Llengües 🇪🇺", es: "Día de las Lenguas 🇪🇺" }, "27-09": { ca: "Dia del Turisme 🏨", es: "Día del Turismo 🏨" }, "28-09": { ca: "Dia de la Rabia 🐶", es: "Día de la Rabia 🐶" }, "29-09": { ca: "Dia del Cor ❤️", es: "Día del Corazón ❤️" }, "30-09": { ca: "Dia del Podcast 🎙️", es: "Día del Podcast 🎙️" },

    // OCTUBRE
    "01-10": { ca: "Gent Gran / Cafè ☕", es: "Tercera Edad / Café ☕" }, "02-10": { ca: "No Violència ✌️", es: "No Violencia ✌️" }, "03-10": { ca: "Dia del Caminar 🚶", es: "Día de Caminar 🚶" }, "04-10": { ca: "Dia dels Animals 🐾", es: "Día de los Animales 🐾" }, "05-10": { ca: "Dia dels Docents 👩‍🏫", es: "Día de los Docentes 👩‍🏫" }, "06-10": { ca: "Dia del Somriure 😊", es: "Día de la Sonrisa 😊" }, "07-10": { ca: "Dia del Treball Digne 💼", es: "Día del Trabajo Digno 💼" }, "08-10": { ca: "Dia de la Visió 👀", es: "Día de la Visión 👀" }, "09-10": { ca: "Comunitat Valenciana 🥘 / Correu ✉️", es: "Comunidad Valenciana 🥘 / Correo ✉️" }, "10-10": { ca: "Salut Mental 🧠", es: "Salud Mental 🧠" }, "11-10": { ca: "Dia de la Nena 👧", es: "Día de la Niña 👧" }, "12-10": { ca: "Festa Nacional 🇪🇸", es: "Fiesta Nacional 🇪🇸" }, "13-10": { ca: "Reducció de Desastres 🌪️", es: "Reducción de Desastres 🌪️" }, "14-10": { ca: "Dia de l'Ou 🥚", es: "Día del Huevo 🥚" }, "15-10": { ca: "Dona Rural 👩‍🌾 / Rentar Mans 🧼", es: "Mujer Rural 👩‍🌾 / Lavar Manos 🧼" }, "16-10": { ca: "Alimentació 🍏", es: "Alimentación 🍏" }, "17-10": { ca: "Erradicació Pobresa 🤝", es: "Erradicación Pobreza 🤝" }, "18-10": { ca: "Dia de la Menopausa ♀️", es: "Día de la Menopausia ♀️" }, "19-10": { ca: "Càncer de Mama 🎀", es: "Cáncer de Mama 🎀" }, "20-10": { ca: "Estadística 📊 / Cuiner 👨‍🍳", es: "Estadística 📊 / Cocinero 👨‍🍳" }, "21-10": { ca: "Dia del Nacho 🧀", es: "Día del Nacho 🧀" }, "22-10": { ca: "Dia de l'Oscil·loscopi 📉", es: "Día del Osciloscopio 📉" }, "23-10": { ca: "Dia del Mol 🧪", es: "Día del Mol 🧪" }, "24-10": { ca: "Nacions Unides 🇺🇳", es: "Naciones Unidas 🇺🇳" }, "25-10": { ca: "Dia de l'Opera 🎼", es: "Día de la Ópera 🎼" }, "26-10": { ca: "Dia del Dany Cerebral 🧠", es: "Día del Daño Cerebral 🧠" }, "27-10": { ca: "Patrimoni Audiovisual 📹", es: "Patrimonio Audiovisual 📹" }, "28-10": { ca: "Dia de l'Animació 🎬", es: "Día de la Animación 🎬" }, "29-10": { ca: "Dia de l'Ictus 🧠", es: "Día del Ictus 🧠" }, "30-10": { ca: "Dia del Llistat 📋", es: "Día del Listado 📋" }, "31-10": { ca: "Halloween / Castanyada 🎃🌰", es: "Halloween / Castañada 🎃🌰" },

    // NOVEMBRE
    "01-11": { ca: "Tots els Sants 🕯️", es: "Todos los Santos 🕯️" }, "02-11": { ca: "Dia de Difunts 💀", es: "Día de Difuntos 💀" }, "03-11": { ca: "Dia del Sandwich 🥪", es: "Día del Sandwich 🥪" }, "04-11": { ca: "Dia de l'Unesco 🏛️", es: "Día de la Unesco 🏛️" }, "05-11": { ca: "Dia dels Tsunamis 🌊", es: "Día de los Tsunamis 🌊" }, "06-11": { ca: "Evitar explotació en guerres 🏳️", es: "Evitar explotación en guerras 🏳️" }, "07-11": { ca: "Dia de la Síl·laba 🗣️", es: "Día de la Sílaba 🗣️" }, "08-11": { ca: "Radiologia 🩻 / Urbanisme 🏗️", es: "Radiología 🩻 / Urbanismo 🏗️" }, "09-11": { ca: "Dia de l'Inventor 💡", es: "Día del Inventor 💡" }, "10-11": { ca: "Dia de la Ciència 🔬", es: "Día de la Ciencia 🔬" }, "11-11": { ca: "Dia del Solter 🕺", es: "Día del Soltero 🕺" }, "12-11": { ca: "Dia de l'Obesitat 🍎", es: "Día de la Obesidad 🍎" }, "13-11": { ca: "Dia de la Bondat 🧡", es: "Día de la Bondad 🧡" }, "14-11": { ca: "Dia de la Diabetis 💉", es: "Día de la Diabetes 💉" }, "15-11": { ca: "Dia sense Alcohol 🚫🍺", es: "Día sin Alcohol 🚫🍺" }, "16-11": { ca: "Tolerància / Flamenc 💃", es: "Tolerancia / Flamenco 💃" }, "17-11": { ca: "Dia de l'Estudiant 🎓", es: "Día del Estudiante 🎓" }, "18-11": { ca: "Dia dels Rècords Guinness 🏆", es: "Día de los Récords Guinness 🏆" }, "19-11": { ca: "Dia de l'Home 🧔", es: "Día del Hombre 🧔" }, "20-11": { ca: "Dia de la Infància 🧸", es: "Día de la Infancia 🧸" }, "21-11": { ca: "Dia de la Televisió 📺", es: "Día de la Televisión 📺" }, "22-11": { ca: "Santa Cecília (Música) 🎶", es: "Santa Cecilia (Música) 🎶" }, "23-11": { ca: "Dia de Fibonacci 🔢", es: "Día de Fibonacci 🔢" }, "24-11": { ca: "Dia de l'Evolució 🐵", es: "Día de la Evolución 🐵" }, "25-11": { ca: "Contra Violència Gènere 💜", es: "Contra Violencia Género 💜" }, "26-11": { ca: "Dia de l'Olivera 🫒", es: "Día del Olivo 🫒" }, "27-11": { ca: "Dia del Mestre 👨‍🏫", es: "Día del Maestro 👨‍🏫" }, "28-11": { ca: "Dia del Mediterrani 🌊", es: "Día del Mediterráneo 🌊" }, "29-11": { ca: "Dia del Jaguar 🐆", es: "Día del Jaguar 🐆" }, "30-11": { ca: "Influencer / Seguretat Informàtica 🤳💻", es: "Influencer / Seguridad Informática 🤳💻" },

    // DESEMBRE
    "01-12": { ca: "Contra la SIDA 🎗️", es: "Contra el SIDA 🎗️" }, "02-12": { ca: "Abolició Esclavitud 🔗", es: "Abolición Esclavitud 🔗" }, "03-12": { ca: "Discapacitat ♿", es: "Discapacidad ♿" }, "04-12": { ca: "Dia dels Bancs 🏦", es: "Día de los Bancos 🏦" }, "05-12": { ca: "Dia del Voluntariat 🙋 / Sòl 🌱", es: "Día del Voluntariado 🙋 / Suelo 🌱" }, "06-12": { ca: "Constitució ⚖️", es: "Constitución ⚖️" }, "07-12": { ca: "Aviació Civil ✈️", es: "Aviación Civil ✈️" }, "08-12": { ca: "La Puríssima ⛪", es: "La Purísima ⛪" }, "09-12": { ca: "Contra la Corrupció 🚫💰", es: "Contra la Corrupción 🚫💰" }, "10-12": { ca: "Drets Humans 📜", es: "Derechos Humanos 📜" }, "11-12": { ca: "Dia de les Muntanyes 🏔️", es: "Día de las Montañas 🏔️" }, "12-12": { ca: "Cobertura Sanitària 🏥", es: "Cobertura Sanitaria 🏥" }, "13-12": { ca: "Santa Llúcia (Llum) 🕯️", es: "Santa Lucía (Luz) 🕯️" }, "14-12": { ca: "Dia del mico 🐒", es: "Día del mono 🐒" }, "15-12": { ca: "Dia del Te 🍵", es: "Día del Té 🍵" }, "16-12": { ca: "Dia de la Lectura a Catalunya 📖", es: "Día de la Lectura en Cataluña 📖" }, "17-12": { ca: "Dia dels volcans 🌋", es: "Día de los volcanes 🌋" }, "18-12": { ca: "Dia del Migrant 🌍", es: "Día del Migrante 🌍" }, "19-12": { ca: "Dia de l'ajuda emocional ❤️", es: "Día de la ayuda emocional ❤️" }, "20-12": { ca: "Solidaritat Humana 🤝", es: "Solidaridad Humana 🤝" }, "21-12": { ca: "Hivern ❄️", es: "Invierno ❄️" }, "22-12": { ca: "Loteria de Nadal 🎰", es: "Lotería de Navidad 🎰" }, "23-12": { ca: "Dia del Festivus 🎪", es: "Día del Festivus 🎪" }, "24-12": { ca: "Nit de Nadal 🍗", es: "Nochebuena 🍗" }, "25-12": { ca: "Nadal 🎄", es: "Navidad 🎄" }, "26-12": { ca: "Sant Esteve 🥣", es: "San Esteban 🥣" }, "27-12": { ca: "Preparació Epidèmies 😷", es: "Preparación Epidemias 😷" }, "28-12": { ca: "Sants Innocents 🃏", es: "Santos Inocentes 🃏" }, "29-12": { ca: "Diversitat Biològica 🌿", es: "Diversidad Biológica 🌿" }, "30-12": { ca: "Dia de la Sagrada Família ⛪", es: "Día de la Sagrada Familia ⛪" }, "31-12": { ca: "Cap d'Any 🥂", es: "Fin de Año 🥂" }
};